# Project information
site_name: WebDyne
#site_url: https://aspeer.github.io/WebDyne/
site_url: https://aspeer.github.io/mkdocs-WebDyne-Doc/
site_author: Andrew Speer
site_description: >-
  Engine for creation of dynamic HTML pages with embedded Perl
#docs_dir: src

# Repository
repo_name: aspeer/WebDyne
#repo_url: https://github.com/aspeer/WebDyne
repo_url: https://github.com/aspeer/mkdocs-WebDyne-Doc

# Copyright
copyright: Copyright &copy; 2025 Andrew Speer

# Configuration
theme:
  name: material
#  custom_dir: material/overrides
  features:
    - announce.dismiss
    ##- content.action.edit
    ##- content.action.view
    ##- content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    ##- content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    ##- navigation.tabs
    # - navigation.tabs.sticky
    ##- navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
    #  RH subsections
    - toc.integrate
    - navigation.sections
    ##- navigation.expand
    - toc.integrate
  navigation:
    tabs: false
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
#  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
#  - minify:
#      minify_html: true
  - awesome-pages
  - redirects:
      redirect_maps:
        index.md: 00_introduction.md 

# Hooks
#hooks:
#  - material/overrides/hooks/shortcodes.py
#  - material/overrides/hooks/translations.py

# Additional configuration
extra:
#  status:
#    new: Recently added
#    deprecated: Deprecated
#  analytics:
#    provider: google
#    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/squidfunk
    - icon: fontawesome/solid/code
      link: https://www.perl.org
      name: Perl
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/squidfunk/mkdocs-material/
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/mkdocs-material/
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/squidfunk.bsky.social
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@squidfunk
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/squidfunk

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: aspeer
      repo: WebDyne
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

#not_in_nav: |
#  /tutorials/**/*.md

# Page tree
#nav:
#  - Introduction: 00_introduction.md
#  - Installation: 03_installation.md
#  - Usage: 05_getting_started_basic_usage_examples.md
#      - ...
#  - Reference: 08_webdyne_api.md
#      - ...
#  - License: 11_gnu_general_public_license_gpl.md
#      - ...
#  - Credits: 06_credits.md
#  - Support: 07_support.md
  
