#  ** BUILD STAGE **
#
FROM ghcr.io/aspeer/webdyne:alpine


#  Work directory
#
WORKDIR /app


#  Build
#
COPY docker/webdyne.conf.pl /etc
COPY docker/cpanfile .
COPY doc/example/*.psp .
COPY doc/example/*.css .


# Expose port 8080
#
EXPOSE 8080


# Set an environment variable (can be overridden at runtime)
#
ENV DOCUMENT_ROOT=/app


# Run the binary with the environment variable
#
#CMD []
